default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: unicode

development:
  <<: *default
  database: tcfreelancers_development
  user: tcfreelancers
  host: localhost

test:
  <<: *default
  database: tcfreelancers_test
  user: tcfreelancers
  host: localhost

production:
  <<: *default
  database: tcfreelancers_production
